behaviors:
  CarAgent:
    trainer_type: sac

    hyperparameters:
      batch_size: 1024
      buffer_size: 20000
      learning_rate: 5e-4
      learning_rate_schedule: linear
      tau: 5e-3                # Soft update coefficient for the target networks
      init_entcoef: 0.2        # Initial entropy regularization coefficient

    network_settings:
      normalize: true
      hidden_units: 512
      num_layers: 3

    reward_signals:
      extrinsic:
        gamma: 0.999
        strength: 1.0

    max_steps: 1e7             # 10 million training steps
    time_horizon: 128
    summary_freq: 50000
